title: Knowledge base
description: Knowledge base
remote_theme: rundocs/jekyll-rtd-theme

url: https://wiki.cristianrz.v6.rocks

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
